# HEY! This file is used in the dbt-artifacts integrations tests with GitHub Actions.
# You should __NEVER__ check credentials into version control. Thanks for reading :)

config:
    send_anonymous_usage_stats: False
    use_colors: True

dbt_artifacts:
  target: bigquery
  outputs:
    bigquery:
      type: bigquery
      method: oauth
      project: "{{ env_var('DBT_ENV_SECRET_GCP_PROJECT') }}"
      dataset: dbt_artifacts_test_commit_{{ env_var('GITHUB_SHA_OVERRIDE', '') if env_var('GITHUB_SHA_OVERRIDE', '') else env_var('GITHUB_SHA', 'toto') }}
      threads: 8
      timeout_seconds: 300
      priority: interactive
      retries: 1
